In [4]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\venkata krishna\Documents\Downloads\bangalore house price prediction cleaned.csv")
df.head(15)

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
5,2,2.0,40.0,1170.0,2,3418.803419,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,2,2.0,65.0,1425.0,3,4561.403509,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,2,2.0,43.0,947.0,2,4540.654699,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,2,2.0,36.0,1130.0,2,3185.840708,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,2,2.0,76.0,1417.0,3,5363.443896,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,2,1.0,58.0,1230.0,2,4715.447154,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11,3,2.0,75.0,1705.0,3,4398.826979,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,2,1.0,47.0,1116.0,2,4211.469534,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
13,2,2.0,40.0,991.0,2,4036.326942,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,1,1.0,27.0,550.0,1,4909.090909,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.tail()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
7115,3,2.0,325.00,2900.0,3,11206.896550,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
import pandas as pd
df=pd.read_excel(r"C:\Users\venkata krishna\Documents\Downloads\house price (1).xlsx",sheet_name="Sheet3")
df[['city','status']]
df1=pd.get_dummies(df[['city','status']])
df2=df[['area','price']]
pd.concat([df1,df2],axis = 1)

,city_ahmadabad,city_vadodra,city_vapi,status_not_sell,status_sell,area,price
0,0,1,0,0,1,2891,518085
1,0,1,0,1,0,3319,565725
2,0,1,0,0,1,3710,813837
3,0,1,0,1,0,2684,696772
4,0,1,0,0,1,2433,547320
5,0,1,0,1,0,2403,920845
6,0,1,0,0,1,3199,850272
7,0,1,0,1,0,2437,537670
8,0,1,0,0,1,2790,565200
9,0,0,1,1,0,3954,638101
10,0,0,1,0,1,3757,590006
11,0,0,1,1,0,2506,994719
12,0,0,1,0,1,2276,605601
13,1,0,0,1,0,3887,902926
14,1,0,0,0,1,3296,577103
15,1,0,0,1,0,2061,556929
16,1,0,0,0,1,3941,673993
17,1,0,0,1,0,3046,679953
18,1,0,0,0,1,3916,612623